# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export CONFIG_LOCATION=$HOME/dotfiles
export OVERRIDE_LOCATION=$HOME/overrides

for conf in "${CONFIG_LOCATION}/shell/zshconfig/"*.zsh; do
  source "${conf}"
done

# local, non-public overrides
if [ -d "${OVERRIDE_LOCATION}/" ] ; then
  for conf in "${OVERRIDE_LOCATION}/"*.zsh; do
    source "${conf}"
  done
fi
unset conf

setopt APPEND_HISTORY

plugins=(git colored-man-pages colorize jump bundler)
source $ZSH/oh-my-zsh.sh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
if [ -f "/usr/share/nvm/init-nvm.sh" ] ; then
  source /usr/share/nvm/init-nvm.sh
fi

# Stop Homebrew from autoupgrading everything when something in their
# dependency tree changes
export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# fzf shell completion
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
