#!/bin/bash
############################
# .make.sh This script creates symlinks from the home directory to any desired
# dotfiles in ~/dotfiles
############################

########## Variables

dir=~/dotfiles                    # dotfiles directory
olddir=~/dotfiles_old             # old dotfiles backup directory
dotfile_dirs="shell git editor terminal"

# create dotfiles_old in homedir
mkdir -p $olddir

# change to the dotfiles directory
cd $dir

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks
for dotfile_dir in $dotfile_dirs; do
  for file in $dir/$dotfile_dir/*; do
    if [ -f "$file" ]; then
      basename=$(basename "$file")
      dirname=$(dirname "$file")
      mv ~/.$basename $olddir
      ln -s $file ~/.$basename
    fi
  done
done

echo "Complete. Moved all existing dotfiles to $olddir."

# Move files in scripts folder to /bin in $HOME
home_bin=$HOME/bin
mkdir -p $home_bin

for file in $dir/scripts/*; do
  if [ -f "$file" ]; then
    scriptname=$(basename "$file")
    ln -s $file $home_bin/$scriptname
  fi
done
