filetype indent plugin on

syntax on

" Turn off backups and swaps
set nobackup
set noswapfile

" Buff up auto-completion
set wildmenu

" Use system clipboard
set clipboard+=unnamedplus

" Show status bar
set laststatus=2

" Show commands in bottom of screen
set showcmd

" Search highlighting (meh?)
set hlsearch

" I think this helps with reload, but I'll read into it later
set nocompatible

" Enable standard backspacing
set backspace=indent,eol,start

" Case insenstive searching
set ignorecase
set smartcase

" Keep indentation for new lines set to current indentation level
set autoindent

" Display line numbers
set number

" Ack ignored regex
set wildignore+=*/.git/*,*/tmp/*,*/.tmp/*,*/.DS_Store/*set,*.swp

" Display cursor position
set ruler

" Turn off line wrapping
set nowrap

" Indentation (setting based off of ruby standards)
set shiftwidth=2
set softtabstop=2
set expandtab

" Change update frequency (added to make gitgutter smoother)
set updatetime=100

" Line guide
set colorcolumn=80,100,120
hi ColorColumn ctermbg=235 guibg=#2c2d27

" Highlighting color
hi Search ctermbg=240 guibg=#725577
hi Visual ctermbg=240 guibg=#725577

"set foldmethod=syntax " Fold using the wisdom of vim.ruby or similar
set foldmethod=manual 
set nofoldenable " Temporarily disable folding when file is first opened

 "Copy relative file path of current buffer to clipboard
noremap <Leader>p :let @+=expand("%")<CR>
 "Copy absolute file path of current buffer to clipboard
noremap <Leader>P :let @+=expand("%:p")<CR>

" utilities for oepning and sourcing configurations
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" utilities for opening alt files (from vim-rails)
nnoremap <leader>av :AV<cr>
nnoremap <leader>as :AS<cr>
nnoremap <leader>al :AT<cr>
nnoremap <leader>a :A<cr>

" abbreviations
iabbrev recieve receive
iabbrev github GitHub

" Remap integer increment (conflicted with tmux overwrite)
" noremap <C-b> <C-a>
" set increment to include alpha characters
set nrformats+=alpha

" Remap escape from insert mode
imap jj <Esc>

" Clear search highlighting
nnoremap <Leader>c :noh<CR>

" fzf view
let g:fzf_layout = { 'down': '~30%' }
" Ack formatting
let g:ackprg = 'ag --nogroup --nocolor --column'

" Open Fern
 map <C-d> :Lexplore<CR>

 " NERD Commenter settings
 " Adds a space after comment insertion
 let g:NERDSpaceDelims = 1

" delimitmate disable <> matching for html to avoid conflicting with close-tag
au FileType html let b:delimitMate_matchpairs = "(:),[:],{:}"

" Tell Vim to treat Jenkinsfile as Groovy script
au BufNewFile,BufRead Jenkinsfile setf groovy

" Turn on spellcheck
au BufNewFile,BufRead *.md setlocal spell
au BufNewFile,BufRead *.yml setlocal spell
au FileType gitcommit setlocal spell

" fzf shortcuts
" stolen from https://rietta.com/blog/hide-gitignored-files-fzf-vim/
" fzf file fuzzy search that respects .gitignore
" If in git directory, show only files that are committed, staged, or unstaged
" else use regular :Files
nnoremap <expr> <Leader>t (len(system('git rev-parse')) ? ':Files' : ':GFiles --exclude-standard --others --cached')."\<CR>"
map <Leader>b :Buffers<CR>

let g:airline_theme='gruvbox'

"remove trailing whitespace
autocmd BufWritePre *.rb :%s/\s\+$//e

" VimTrick to close all open buffers except current
" https://www.getrevue.co/profile/vim_tricks/issues/closing-hidden-buffers-1171538
command Bd :up | %bd | e#

" vim-test shortcuts
" run tests in current buffer. If there are no tests, run last test again
nmap <silent> <leader>T :TestFile<CR>
" run last test
nmap <silent> <leader>Tl :TestLast<CR>
" open last test run & run again
nmap <silent> <leader>Tv :TestVisit<CR>

let test#strategy = 'neovim'

" #################################################
" #                 ALE settings                  #
" #################################################
" `:h ale-options` for details
let g:ale_enabled = 1

let g:ale_fix_on_save = 1

" remove ALE gutter background color
highlight clear ALEErrorSign
highlight clear ALEWarningSign

" remove syntax highlighting
let g:ale_set_highlights = 0

" turn off error virtual text
let g:ale_virtualtext_cursor = 'disabled'

" set ALE warning/error symbols
let g:ale_sign_error = '!!'
let g:ale_sign_warning = '!'

" set ALE error presentation
"   echo_msg_format is what appears below the statusline
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_echo_msg_format =
    \ '[%linter%] %code%: %s'

"   loclist_msg_format is what appears in loclist
let g:ale_loclist_msg_error_str = 'Error'
let g:ale_loclist_msg_info_str = 'Info'
let g:ale_loclist_msg_warning_str = 'Warning'
let g:ale_loclist_msg_format =
    \ '[%linter%]%code% | %s (%severity%)'

" Specify linters per language.
"   Takes a list of linters,
"     the string 'all' (or removing the key) returns to default
let s:default_linters =
    \{
    \   'ruby': ['rubocop', 'ruby'],
    \   'markdown': ['write-good'],
    \}

let js_fixers = ['prettier', 'eslint']
let g:ale_fixers = {
    \   'ruby': ['rubocop'],
    \   'javascript': js_fixers,
    \   'javascript.jsx': js_fixers,
    \   'typescript': js_fixers,
    \   'typescriptreact': js_fixers,
    \   'css': ['prettier'],
    \   'json': ['prettier'],
    \   'yaml': ['prettier'],
    \   'yml': ['prettier'],
    \}

let g:ale_linters = s:default_linters

" Individual linter options
" ALE keybindings
"   show full message for current line
nmap <silent> <Leader>d <Plug>(ale_detail)

" #################################################
" #             End ALE settings                  #
" #################################################

call plug#begin('~/.vim/plugged')
  " file management and movement
  Plug 'christoomey/vim-tmux-navigator'
  Plug 'junegunn/fzf'
  Plug 'junegunn/fzf.vim'
  Plug 'mileszs/ack.vim'
  Plug 'tpope/vim-vinegar'

  " git
  Plug 'airblade/vim-gitgutter'
  Plug 'rbong/vim-flog'
  Plug 'tpope/vim-fugitive'
  Plug 'tpope/vim-rhubarb'

  " ruby
  Plug 'joker1007/vim-ruby-heredoc-syntax'
  Plug 'kana/vim-textobj-user'
  Plug 'nelstrom/vim-textobj-rubyblock'
  Plug 'tpope/vim-bundler'
  Plug 'tpope/vim-rails'
  Plug 'vim-ruby/vim-ruby'

  " js/frontend
  Plug 'alvan/vim-closetag'
  Plug 'mattn/emmet-vim'
  Plug 'pangloss/vim-javascript'
  Plug 'petrbroz/vim-glsl'

  " appearance
  Plug 'ap/vim-css-color'
  Plug 'mechatroner/rainbow_csv'
  Plug 'morhetz/gruvbox'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'

  " usability
  Plug 'AndrewRadev/splitjoin.vim'
  Plug 'Raimondi/delimitMate'
  Plug 'dense-analysis/ale'
  Plug 'editorconfig/editorconfig-vim'
  Plug 'ervandew/supertab'
  Plug 'godlygeek/tabular'
  Plug 'izzergh/rumpelstiltskin'
  Plug 'preservim/nerdcommenter'
  Plug 'rsrchboy/vim-textobj-heredocs'
  Plug 'terryma/vim-expand-region'
  Plug 'terryma/vim-multiple-cursors'
  Plug 'tpope/vim-abolish'
  Plug 'tpope/vim-endwise'
  Plug 'tpope/vim-eunuch'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-unimpaired'
  Plug 'vim-test/vim-test'

  " copilot
  Plug 'github/copilot.vim'
call plug#end()

" autocmd vimenter * ++nested 
colorscheme gruvbox
hi Normal guibg=NONE ctermbg=NONE
hi clear SignColumn
